add secretBox API
haskell-cryptography/cryptography-libsodium-bindings pull request #28
Opened 2022-05-08 08:12 UTC by TeofilC

This patch adds bindings to Libsodium's secretbox API (#24).

I've not added bindings to the NaCl compatibility bindings as they are deprecated.

Feedback is appreciated.

2022-05-08 09:03 UTC, TeofilC commented
I've force pushed after formatting the cabal file with cabal-fmt

2022-05-19 20:35 UTC, Kleidukos requested changes
Hi @TeofilC! Thank you very much for this PR. :) 

This looks good overall. Except for the `@since` annotation remark, the only thing I'd like to ask would be to follow the convention in the SHA2 module, and add a little:

```markdown
-- /See also:/ [crypto_hash_sha256()](https://doc.libsodium.org/advanced/sha-2_hash_function#sha-256)
```

type of line at the end of each haddock paragraph. :)

2022-05-19 20:35 UTC, Kleidukos commented on src/Cryptography/Sodium/Bindings/Secretbox.hs
> +-- | The length of a secretbox authentication tag in bytes.
Forgotten `@since` annotation

2022-05-25 17:16 UTC, TeofilC commented on src/Cryptography/Sodium/Bindings/Secretbox.hs
> +-- | The length of a secretbox authentication tag in bytes.
Good spot! Fixed in 8047551

2022-05-25 17:18 UTC, TeofilC commented
Thanks for the review @Kleidukos . I've applied the changes you've suggested. Let me know if my changes are what you had in mind

2022-05-25 17:49 UTC, Kleidukos requested changes
Almost there! I think it should be good after this one. :)

2022-05-25 17:49 UTC, Kleidukos commented on src/Cryptography/Sodium/Bindings/Secretbox.hs
> +--   [easy] Both the ciphertext and authentication tag are stored in the smae buffer.
```suggestion
--   [easy] Both the ciphertext and authentication tag are stored in the same buffer.
```

2022-05-25 17:49 UTC, Kleidukos commented on src/Cryptography/Sodium/Bindings/Secretbox.hs
> +-- A key can be generated using the 'cryptoSecretboxKeygen' primitive
```suggestion
-- A key can be generated using the 'cryptoSecretboxKeygen' primitive.
```

2022-05-25 17:49 UTC, Kleidukos commented on src/Cryptography/Sodium/Bindings/Secretbox.hs
> +-- See also: [Detached mode](https://doc.libsodium.org/secret-key_cryptography/secretbox#detached-mode)
```suggestion
-- /See also:/ [crypto_secretbox_keygen()](https://doc.libsodium.org/secret-key_cryptography/secretbox#detached-mode)
```

2022-05-25 17:49 UTC, Kleidukos commented on src/Cryptography/Sodium/Bindings/Secretbox.hs
> +-- See also: [Combined mode](https://doc.libsodium.org/secret-key_cryptography/secretbox#combined-mode)
```suggestion
-- /See also:/ [crypto_secretbox_easy()](https://doc.libsodium.org/secret-key_cryptography/secretbox#combined-mode)
```

2022-05-25 17:49 UTC, Kleidukos commented on src/Cryptography/Sodium/Bindings/Secretbox.hs
> +-- See also: [Combined mode](https://doc.libsodium.org/secret-key_cryptography/secretbox#combined-mode)
```suggestion
-- /See also:/ [crypto_secretbox_open_easy()](https://doc.libsodium.org/secret-key_cryptography/secretbox#combined-mode)
```

2022-05-25 17:49 UTC, Kleidukos commented on src/Cryptography/Sodium/Bindings/Secretbox.hs
> +-- See also: [Detached mode](https://doc.libsodium.org/secret-key_cryptography/secretbox#detached-mode)
```suggestion
-- /See also:/ [crypto_secretbox_detached()](https://doc.libsodium.org/secret-key_cryptography/secretbox#detached-mode)
```

2022-05-25 17:49 UTC, Kleidukos commented on src/Cryptography/Sodium/Bindings/Secretbox.hs
> +-- See also: [Detached mode](https://doc.libsodium.org/secret-key_cryptography/secretbox#detached-mode)
```suggestion
-- /See also:/ [crypto_secretbox_open_detached()](https://doc.libsodium.org/secret-key_cryptography/secretbox#detached-mode)
```

2022-05-25 18:55 UTC, Kleidukos requested changes
Alright, one more waltz and I guarantee you I'm merging it this evening. :)

2022-05-25 19:01 UTC, TeofilC commented
No worries thanks for spotting! should be fixed

2022-05-25 20:13 UTC, Kleidukos approved these changes
Nice.

2022-05-26 01:10 UTC, merged